replicaCount: 1

image:
  repository: 307654411660.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: 1b47e81356ec5a16156bd8263989b19f9ae1c11e
  pullPolicy: Always

service:
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: development