replicaCount: 1

image:
  repository: 307654411660.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: 28e316cb20182a6fc02af55f48b48e3f70eb2d90
  pullPolicy: Always

service:
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: development