replicaCount: 2

image:
  repository: 307654411660.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: 3ed52ee4d012e478535a7b7db3870f342eb78eb9
  pullPolicy: Always

service:
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: production