replicaCount: 2

image:
  repository: 307654411660.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: bc8825d018f99ac93e8744184ee6efec8926c898
  pullPolicy: Always

service:
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: production