replicaCount: 2

image:
  repository: 307654411660.dkr.ecr.us-west-2.amazonaws.com/my-app
  tag: c9c85fa5cf266d393c3509c2ffbd590ab8bca098
  pullPolicy: Always

service:
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: production